# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    
env:
  PORT: ${{ secrets.PORT }}
  MONGO_ADMIN: ${{ secrets.MONGO_ADMIN }}
  MONGO_AUTH: ${{ secrets.MONGO_AUTH }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  CLIENT_URL: ${{ secrets.CLIENT_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
  
    - name: 'Create env file'
      run: |
          touch .env
          echo MONGODB_URI=$MONGODB_URI >> .env
          echo PORT=$PORT >> .env
          echo MONGO_ADMIN=$MONGO_ADMIN >> .env
          echo MONGO_AUTH=$MONGO_AUTH >> .env
          echo CLIENT_URL=$CLIENT_URL >> .env
          echo JWT_SECRET=$JWT_SECRET >> .env
    - run: npm ci
    - run: npm run build --if-present
